---
title: "final_analysis"
author: "Kyle Monper"
date: "March 6, 2020"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = T)
```


```{r}
library(tidyverse)
library(stargazer)

yearlydata <- read_csv("yearlydata.csv")
all_data <- read_csv("all_data.csv") #%>% # In original csv, search and replaced cage column "Small" with "small" and "Big" with "big"
  #filter(janrain != "NA")
precip <- read_csv("water_year.csv") %>% 
  select(-year)
```

```{r separate cages}

yearly_small <- yearlydata %>% 
  filter(cage == "small")
yearly_big <- yearlydata %>% 
  filter(cage == "big")
yearly_none <- yearlydata %>% 
  filter(cage == "none")
```


### GLMs
```{r}
## fecundity
fecund_model <- glm(avgseedpods ~ janrain + febrain + marchrain + aprilrain + caged  , data = yearlydata, family = poisson) 
summary(fecund_model)


### germination
germ_model <- glm(cbind(germination, bank - germination) ~ decrain + janrain, data = yearlydata, family=binomial())
summary(germ_model)


## flower
flower_model <- glm(cbind(reproductive, earlydeath) ~ febrain + marchrain + aprilrain + caged, data = yearlydata, family = binomial)
summary(flower_model)

```



```{r function}

## find max fecundity for the no cage scenario
fecund <- yearly_none %>% 
  filter(reproductive > 0) %>% 
  select(avgseedpods) 

max_f_none <- max(fecund$avgseedpods)

fecund <- yearly_big %>% 
  filter(reproductive > 0) %>% 
  select(avgseedpods) 

max_f_big <- max(fecund$avgseedpods, na.rm = T)

fecund <- yearly_small %>% 
  filter(reproductive > 0) %>% 
  select(avgseedpods) 

max_f_small <- max(fecund$avgseedpods)
  

## exogenous drivers -- should be generated on a microhabitat/treatment basis
# d <-  # death rate of seeds (how can we figure this out!?!)
# f <-  # fecundity - note: need to find a way to model this so we can randomize based on some known mean and sd
# g <-  # germination rate -- (same note^^^)


sim_lupin <- function(planted, cage_type) {
  
  N <- vector(length = 5)
  b <- vector(length = 6)
  b[1] <- planted
  
  d <- .17
  
  ## randomize years to be selected
  years <- ceiling(runif(5, 0, 13))
  
  ## get random precip years + add cage type to df to be used w/in predict
  precip$caged <- cage_type
  precip_year <- precip[years,]
  
  f <- predict(fecund_model, precip_year, type = "response") * 2 # x2 for number of sees per pod
  f[f<0] <- 0
  
  ## need to figure out the proper distribution for these ( for each treatment type?)
  g <- predict(germ_model, precip_year, type = "response")
  g[g<0] <- 0
  
  s <- predict(flower_model, precip_year, type = "response")
  s[s<0] <- 0
  

  for(year in 1:5) {
    N[year] <- b[year]* (1 - d) * g[year] 
    b[year + 1] <- (N[year]* s[year] * f[year]) + (b[year] - (N[year]))
  }
  
  res <- data.frame(year = seq(1,5), pop = N[1:5], bank = b[1:5])
  res$scenario <- planted
  
  return(res)
  
}

test <- sim_lupin(1000, "Caged")
test

```

```{r stargazer tables, results = 'asis', echo = FALSE}
# Stargazer table of germination glm
library(stargazer)

model_table <- stargazer(germ_model, fecund_model,
                        type = "html",
                        single.row = TRUE,
                        dep.var.labels = c("Germination","Fecundity"),
                        covariate.labels = c("Dec Rain","Jan Rain","Feb Rain","Mar Rain","Apr Rain","May Rain","Big Cage","No Cage","Small Cage")
                        )
model_table

```



# single run - big cage
```{r simulate}
### how to choose necessary planting

planted <- seq(100, 1000, 10)

sim_list <- lapply(planted, sim_lupin, "Caged")

sim <- bind_rows(sim_list)
seeds_needed <- sim %>% 
  filter(year == 5 & pop > 5000) %>% 
  filter(scenario == min(scenario)) %>% ### do we want to select the min or average here?
  select(scenario) %>% 
  as.numeric()


## next to do: monte-carlo simulation to see how randomness effects each of these



# plot the trend
ggplot(sim, aes(year, pop, group = as.factor(scenario), color = as.factor(scenario))) +
  geom_line() +
  geom_hline(yintercept = 5000, linetype = "dashed", size = 1) +
  scale_y_continuous(limits = c(0,7000)) +
  theme_bw() +
  theme(legend.position = "none")


```


# montecarlo run caged
```{r monte carlo}
### this is for if we know the mean and sd for death, fecundity, and germination
## if any of these are unknown, see the MonteCarlo simulation in ./MonteCarlo.Rmd

num_trials <- 1000

trial <- vector(length = num_trials)

planted <- seq(100, 6000, 100)


suppressWarnings({
  for (i in 1:length(trial)) {
  sim_list <- lapply(planted, sim_lupin, "Caged")

  sim <- bind_rows(sim_list)
  
  seeds_needed <- sim %>% 
    filter(year == 5 & pop > 5000) %>% 
    filter(scenario == min(scenario)) %>% ### do we want to select the min or average here?
    select(scenario) %>% 
    as.numeric()
  
  
  
  trial[i] <- seeds_needed
  
  # mark progress (for sanity's sake)
  if(i%%100 == 0) {
    print(paste(i/length(trial)))
  }

  
}
  
})


hist(trial, main = "Caged treatment")

# mean and sd of seeds needed (is the mode more appropriate here?)
mean_big <- mean(trial, na.rm = T)
sd_big <- sd(trial, na.rm = T)

mean_big
sd_big

```




# montecarlo run no cage
```{r monte carlo no}
### this is for if we know the mean and sd for death, fecundity, and germination
## if any of these are unknown, see the MonteCarlo simulation in ./MonteCarlo.Rmd

num_trials <- 100

trial <- vector(length = num_trials)

planted <- seq(1000, 30000, 1000)

suppressWarnings({ 
  for (i in 1:length(trial)) {
  sim_list <- lapply(planted, sim_lupin, "No Cage")

  sim <- bind_rows(sim_list)
  
  seeds_needed <- sim %>% 
    filter(year == 5 & pop > 5000) %>% 
    filter(scenario == min(scenario)) %>% ### do we want to select the min or average here?
    select(scenario) %>% 
    as.numeric()
  
  trial[i] <- seeds_needed
  
  # mark progress (for sanity's sake)
  if(i%%100 == 0) {
    print(paste(i/length(trial)))
  }

  
}})


hist(trial, main = "no cage treatment")

# mean and sd of seeds needed 
mean_none <- mean(trial, na.rm = T)
sd_none <- sd(trial, na.rm = T)

mean_none
sd_none


```

