---
title: "final_analysis"
author: "Kyle Monper"
date: "March 6, 2020"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = F, message = F, echo = T)
```


```{r}
library(tidyverse)
library(knitr)
library(kableExtra)
library(stargazer)

yearlydata <- read_csv("yearlydata.csv")
all_data <- read_csv("all_data.csv") #%>% # In original csv, search and replaced cage column "Small" with "small" and "Big" with "big"
  #filter(janrain != "NA")
precip <- read_csv("water_year.csv") %>% 
  select(-year)
```

### GLMs
```{r}
## fecundity
fecund_model <- glm(avgseedpods ~ janrain + febrain + marchrain + aprilrain + caged  , data = yearlydata, family = poisson) 
summary(fecund_model)


### germination
germ_model <- glm(cbind(germination, bank - germination) ~ decrain + janrain, data = yearlydata, family=binomial())
summary(germ_model)


## flower
flower_model <- glm(cbind(reproductive, earlydeath) ~ febrain + marchrain + aprilrain + caged, data = yearlydata, family = binomial)
summary(flower_model)

```



```{r function}

## find max fecundity for the no cage scenario
fecund <- yearlydata %>% 
  filter(reproductive > 0) %>% 
  select(avgseedpods) 

max_f <- max(fecund$avgseedpods, na.rm = T)




  

## exogenous drivers -- should be generated on a microhabitat/treatment basis
# d <-  # death rate of seeds (how can we figure this out!?!)
# f <-  # fecundity - note: need to find a way to model this so we can randomize based on some known mean and sd
# g <-  # germination rate -- (same note^^^)


sim_lupin <- function(planted, cage_type) {
  
  N <- vector(length = 5)
  b <- vector(length = 6)
  b[1] <- planted
  
  d <- .17
  
  ## randomize years to be selected
  years <- ceiling(runif(5, 0, 13))
  
  ## get random precip years + add cage type to df to be used w/in predict
  precip$caged <- cage_type
  precip_year <- precip[years,]
  
  f <- predict(fecund_model, precip_year, type = "response") * 2 # x2 for number of sees per pod
  f[f<max_f] <- max_f
  
  ## need to figure out the proper distribution for these ( for each treatment type?)
  g <- predict(germ_model, precip_year, type = "response")
  g[g<0] <- 0
  
  s <- predict(flower_model, precip_year, type = "response")
  s[s<0] <- 0
  

  for(year in 1:5) {
    N[year] <- b[year]* (1 - d) * g[year] 
    b[year + 1] <- (N[year]* s[year] * f[year]) + (b[year] - (N[year]))
  }
  
  res <- data.frame(year = seq(1,5), pop = N[1:5], bank = b[1:5])
  res$scenario <- planted
  
  return(res)
  
}

test <- sim_lupin(1000, "Caged")
test

```

```{r stargazer tables, results = 'asis', echo = FALSE}
# Stargazer table of germination glm
library(stargazer)

model_table <- stargazer(germ_model, fecund_model,
                        type = "html",
                        single.row = TRUE,
                        dep.var.labels = c("Germination","Fecundity"),
                        covariate.labels = c("Dec Rain","Jan Rain","Feb Rain","Mar Rain","Apr Rain","May Rain","Big Cage","No Cage","Small Cage")
                        )
model_table

```



```{r}
num_trials <- 5000

needed <- vector()
suppressWarnings({ 
for (i in 1:num_trials){
  
  single <- sim_lupin(1000, "Caged")
# plants per seed
pps <- single %>% 
  mutate(pps = pop/scenario) %>% 
  filter(year == 5) %>% 
  select(pps) %>% 
  as.numeric

needed[i] <- 5000/pps


}})

hist(needed, main = "caged")

## summary
mean_cage <- mean(needed)
sd_cage <- sd(needed)
range_cage <- summary(needed)

mean_cage 
sd_cage
range_cage 

```


```{r}
num_trials <- 5000

needed_no <- vector()

suppressWarnings({ 
for (i in 1:num_trials){
  
  single <- sim_lupin(1000, "No Cage")
# plants per seed
pps <- single %>% 
  mutate(pps = pop/scenario) %>% 
  filter(year == 5) %>% 
  select(pps) %>% 
  as.numeric

needed_no[i] <- 5000/pps

  
}})

hist(needed_no, main = "No Cage")

mean_cage <- mean(needed_no)
sd_cage <- sd(needed_no)
range_cage <- summary(needed_no)

mean_cage 
sd_cage 
range_cage 


```



## table of observed data by cage type
```{r, fig.width=4}
test <- yearlydata %>% 
  group_by(current.year, caged) %>% 
  summarise(
    total = sum(germination)
  )
test
  
table <- test %>% 
  spread(caged, total)

kable(table) %>% 
  kable_styling()
```



# plot
```{r plots}
new_needed <- needed
new_no <- needed_no

## if larger than some value, turn into other value
new_needed[new_needed > 4800] <- 4801
new_no[new_no > 48000] <- 48001

caged <- data.frame(count = new_needed)
no_cage <- data.frame(count = new_no)



ggplot(caged, aes(count)) +
  geom_histogram(breaks = seq(0,5000,200),
                 col = "black",
                 fill = "grey") +
  scale_x_continuous(limits=c(0, 5000), breaks=c(seq(0, 5000, by=200)), labels=c(seq(0,4800, by=200), "5000+"), expand = c(0,10)) +
  scale_y_continuous(expand = c(0,0)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Number of seeds needed")

ggplot(no_cage, aes(count)) +
  geom_histogram(breaks = seq(0,50000,2000),
                 col = "black",
                 fill = "grey") +
  scale_x_continuous(limits=c(0, 50000), breaks=c(seq(0, 50000, by=2000)), labels=c(seq(0,48000, by=2000), "50000+"), expand = c(0,10)) +
  scale_y_continuous(expand = c(0,0)) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))  +
  labs(x = "Number of seeds needed")

```





















