---
title: "test"
author: "Kyle Monper"
date: "February 5, 2020"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MonteCarlo)
library(tidyverse)


precip$cage <- "Big"
tmp <- predict(fecund_model, precip)
```




### new simulation function with means and sds as input variable
```{r new simulation function}

fecund_model <- glm(seedpods ~ decrain + janrain + febrain + marchrain + aprilrain + mayrain + cage, data = all_data, family = poisson) 
summary(fecund_model)

germ_model <- glm(cbind(germination, bank - germination) ~ decrain + janrain, data = germ_pct, family=binomial())

sim_lupin <- function(planted, cage_type) {
  
    
  N <- vector(length = 5)
  b <- vector(length = 6)
  b[1] <- planted
  
  d <- .17
  
  ## randomize years to be selected
  years <- ceiling(runif(5, 0, 13))
  
  ## get random precip years + add cage type to df to be used w/in predict
  precip$cage <- cage_type
  precip_year <- precip[years,]
  
  f <- predict(fecund_model, precip_year, type = "response") * 2 # x2 for number of sees per pod
  f[f<0] <- 0

  
  ## need to figure out the proper distribution for these ( for each treatment type?)
  g <- predict(germ_model, precip_year, type = "response")
  g[g<0] <- 0

  for(year in 1:5) {
    N[year] <- b[year]* (1 - d) * g[year]
    b[year + 1] <- (N[year] * f[year]) + (b[year] - N[year])
  }
  
  res <- data.frame(year = seq(1,5), pop = N[1:5], bank = b[1:5])
  res$scenario <- planted
  
  return(res)
  
}

test <- sim_lupin(1000, "Big")
test
```


### function for calculating the min number of seeds to reach 5000 individuals based on the above
```{r}

calc_seeds <- function(planted, cage_tpye) {
  
  sim_list <- lapply(planted, sim_lupin, cage_type)

  sim <- bind_rows(sim_list)
  
  seeds_needed <- sim %>% 
    filter(year == 5 & pop > 5000) %>% 
    filter(scenario == min(scenario)) %>% ### do we want to select the min or average here?
    select(scenario) %>% 
    as.numeric()
  
  return(list("seeds_needed"=seeds_needed))
  
}
  
test <- calc_seeds(seq(5000, 10000, 100), "Big")


```



```{r}

calc_seeds <- function(d_mean, d_sd, f_mean, f_sd, g_mean, g_sd) {
  
  planted <- seq(5000, 10000, 100)
  
     sim_list <- lapply(planted, sim_lupin, g_mean, cage_type)

  sim <- bind_rows(sim_list)
  
  seeds_needed <- sim %>% 
    filter(year == 5 & pop > 5000) %>% 
    filter(scenario == min(scenario)) %>% ### do we want to select the min or average here?
    select(scenario) %>% 
    as.numeric()
  
  return(list("seeds_needed"=seeds_needed))
  
}


germ_mean <- seq(.01, .05, .01)
cage_type <- c("Big", "none", "small")

param_list=list("d_mean"=death_mean, "d_sd" = death_sd, "f_mean" = fec_mean, "f_sd" = fec_sd, "g_mean" = germ_mean, "g_sd" = germ_sd)


```

```{r run MC}
### 100 reps takes ~ 25 mins
# Sys.time()
# MC_result<-MonteCarlo(func=calc_seeds, nrep=100, param_list=param_list, max_grid = 10000)
# Sys.time()

# write results to df & csv
# results <- MakeFrame(MC_result)
# write_csv(results, "mc_results.csv")

```

```{r}
mc_res <- read_csv("mc_results.csv")

ggplot(mc_res, aes(d_mean, seeds_needed, color = factor(g_mean))) +
  geom_boxplot() +
  facet_wrap(~f_mean)
```





