---
title: "Precipitation_Wrangling"
author: "Robert Saldivar"
date: "March 4, 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
#Loading the tidyverse, lubridate and the data

library(tidyverse)
library(lubridate)
library(here)
library(janitor)

precipitation <- read_csv("preciptiation_data_lupine.csv")

```

```{r}
# THis is going to clean the data so that the prcipitation data can eventually be grouped by month and year

precipitation_clean <- precipitation %>%
  clean_names()


```

```{r}
#for using lubridate
precip_date <- precipitation_clean %>%
  mutate(yr_mo_day = lubridate::parse_date_time(date, "ymd")) %>%
  mutate(month = month(yr_mo_day)) %>%
  mutate(year = year(yr_mo_day)) %>%
  mutate(day = day(yr_mo_day)) %>%
  select(station, precip, month, year, day) %>%
  drop_na()
```


```{r}
#This code chuck is going to summarize the precipitation data so that 

precip_monthly <- precip_date %>%
  group_by(month, year) %>%
  summarize(precip_mean = sum(precip)) %>% 
  ungroup() %>% 
  mutate(precip_mm = precip_mean * 25.4)
  

water_year <- precip_monthly %>% 
  mutate(wym = if_else(month > 9, month - 9, month + 3)) %>% 
  select(-month, -precip_mean)

precip_long <- water_year %>% 
  spread(wym, precip_mm) %>% 
  select(year, decrain = 3, janrain = 4, febrain = 5, marchrain = 6, aprilrain = 7, mayrain = 8) %>% 
  filter(!is.na(aprilrain))

write_csv(precip_long, "water_year.csv")

#precipitation is in inches
```










