---
title: "LUNIPollenRAW"
author: "justin luong"
date: "August 22, 2017"
output: word_document
---

```{r setup}
LUNIpollen <- read.csv("C:/Users/Justin Luong/Desktop/Stats/csv/pollencompile.csv")
```
```{r ply}
require(plyr)
library(plyr)
require(grid)
library(gridExtra)
require(ggplot2)


summary(lm(orderdiversity~plantdiversity, data=LUNIpollen))
plot(orderdiversity~plantdiversity, data=LUNIpollen)

summary(lm(hemipteradiversity~plantdiversity, data=LUNIpollen))
plot(hemipteradiversity~plantdiversity, data=LUNIpollen)

summary(lm(hemipteraabundance~plantdiversity, data=LUNIpollen))
plot(hemipteraabundance~plantdiversity, data=LUNIpollen)

summary(lm(dipteradiversity~plantdiversity, data=LUNIpollen))
plot(dipteradiversity~plantdiversity, data=LUNIpollen)

summary(lm(dipteraabundance~plantdiversity, data=LUNIpollen))
plot(dipteraabundance~plantdiversity, data=LUNIpollen)

summary(lm(hymenopteradiversity~plantdiversity, data=LUNIpollen))
plot(hymenopteradiversity~plantdiversity, data=LUNIpollen)

summary(lm(hymenopteraabudnance~plantdiversity, data=LUNIpollen))
plot(hymenopteraabudnance~plantdiversity, data=LUNIpollen)

summary(lm(CLAMnum~plantdiversity, data=LUNIpollen))
plot(CLAMnum~plantdiversity, data=LUNIpollen)

summary(lm(predatorabudance~plantdiversity, data=LUNIpollen))
plot(predatorabudance~plantdiversity, data=LUNIpollen)

summary(lm(predperplant~plantdiversity, data=LUNIpollen))
plot(predperplant~plantdiversity, data=LUNIpollen)

summary(lm(predatordiversity~plantdiversity, data=LUNIpollen))
plot(predatordiversity~plantdiversity, data=LUNIpollen)

summary(lm(herbivorediversity~plantdiversity, data=LUNIpollen)) # suggested
plot(herbivorediversity~plantdiversity, data=LUNIpollen)

m_herbplant <- function(LUNIpollen){
    m <- lm(herbivorediversity~plantdiversity, LUNIpollen);
    eq <- substitute(italic(y) == a + b%.%italic(x)*","~~italic(R)^2~"="~r2, 
         list(a = format(coef(m)[1], digits = 3), 
              b = format(coef(m)[2], digits = 2), 
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq));
    }
herb_plant <- ggplot(aes(x=plantdiversity,y=herbivorediversity),data=LUNIpollen)+geom_point()+geom_smooth(method = "lm")+xlab("Plant Diversity Per Plot")+ylab("Herbivore Diversity")+theme(panel.border=element_rect(color="black",size=1,fill=NA))+geom_text(aes(x=19, y=9.25, label =lm_orderpod(LUNIpollen)), size=4, parse = TRUE)

summary(lm(herbivoreperplant~plantdiversity, data=LUNIpollen))
plot(herbivoreperplant~plantdiversity, data=LUNIpollen)

summary(lm(herbivoreabundance~plantdiversity, data=LUNIpollen))
plot(herbivorepeabundance~plantdiversity, data=LUNIpollen)

summary(lm(hemipteraperplant~plantdiversity, data=LUNIpollen))
plot(hemipteraperplant~plantdiversity, data=LUNIpollen)

summary(lm(coleopteraperplant~plantdiversity, data=LUNIpollen))
plot(coleopteraperplant~plantdiversity, data=LUNIpollen)

summary(lm(thripsperplant~plantdiversity, data=LUNIpollen))
plot(thripsperplant~plantdiversity, data=LUNIpollen)




summary(lm(orderdiversity~native, data=LUNIpollen))
plot(orderdiversity~native, data=LUNIpollen)

summary(lm(hemipteradiversity~native, data=LUNIpollen))
plot(hemipteradiversity~native, data=LUNIpollen)

summary(lm(hemipteraabundance~native, data=LUNIpollen))
plot(hemipteraabundance~native, data=LUNIpollen)

summary(lm(dipteradiversity~native, data=LUNIpollen))
plot(dipteradiversity~native, data=LUNIpollen)

summary(lm(dipteraabundance~native, data=LUNIpollen))
plot(dipteraabundance~native, data=LUNIpollen)

summary(lm(hymenopteradiversity~native, data=LUNIpollen))
plot(hymenopteradiversity~native, data=LUNIpollen)

summary(lm(hymenopteraabudnance~native, data=LUNIpollen))
plot(hymenopteraabudnance~native, data=LUNIpollen)

summary(lm(CLAMnum~native, data=LUNIpollen))
plot(CLAMnum~native, data=LUNIpollen)
```

```{r}
summary(lm(predatorabudance~avgpod, data=LUNIpollen))
plot(predatorabudance~avgpod, data=LUNIpollen)

summary(lm(predperplant~avgpod, data=LUNIpollen))
plot(predperplant~avgpod, data=LUNIpollen)

summary(lm(predatordiversity~avgpod, data=LUNIpollen))
plot(predatordiversity~avgpod, data=LUNIpollen)

summary(lm(herbivorediversity~avgpod, data=LUNIpollen)) 
plot(herbivorediversity~avgpod, data=LUNIpollen)

summary(lm(herbivoreperplant~avgpod, data=LUNIpollen))
plot(herbivoreperplant~avgpod, data=LUNIpollen)

summary(lm(herbivoreabundance~avgpod, data=LUNIpollen))
plot(herbivorepeabundance~avgpod, data=LUNIpollen)

summary(lm(hemipteraperplant~avgpod, data=LUNIpollen))
plot(hemipteraperplant~avgpod, data=LUNIpollen)

summary(lm(coleopteraperplant~avgpod, data=LUNIpollen))
plot(coleopteraperplant~avgpod, data=LUNIpollen)

summary(lm(thripsperplant~avgpod, data=LUNIpollen))
plot(thripsperplant~avgpod, data=LUNIpollen)

summary(lm(orderdiversity~avgpod, data=LUNIpollen)) #suggested
plot(orderdiversity~avgpod, data=LUNIpollen)

summary(lm(hemipteradiversity~avgpod, data=LUNIpollen)) 
plot(hemipteradiversity~avgpod, data=LUNIpollen)

summary(lm(hemipteraabundance~avgpod, data=LUNIpollen)) #suggested
plot(hemipteraabundance~avgpod, data=LUNIpollen)

summary(lm(dipteradiversity~avgpod, data=LUNIpollen)) #sig
plot(dipteradiversity~avgpod, data=LUNIpollen)

summary(lm(dipteraabundance~avgpod, data=LUNIpollen))
plot(dipteraabundance~avgpod, data=LUNIpollen)

summary(lm(hymenopteradiversity~avgpod, data=LUNIpollen))
plot(hymenopteradiversity~avgpod, data=LUNIpollen)

summary(lm(hymenopteraabudnance~avgpod, data=LUNIpollen))
plot(hymenopteraabudnance~avgpod, data=LUNIpollen)

summary(lm(CLAMnum~avgpod, data=LUNIpollen))
plot(CLAMnum~avgpod, data=LUNIpollen)

summary(lm(thrips~avgpod, data=LUNIpollen))
plot(thrips~avgpod, data=LUNIpollen)

lm_orderpod <- function(LUNIpollen){
    m <- lm(avgpod ~ orderdiversity, LUNIpollen);
    eq <- substitute(italic(y) == a + b%.%italic(x)*","~~italic(R)^2~"="~r2, 
         list(a = format(coef(m)[1], digits = 3), 
              b = format(coef(m)[2], digits = 2), 
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq));
    }
order_pod <- ggplot(aes(x=avgpod,y=orderdiversity),data=LUNIpollen)+geom_point()+geom_smooth(method = "lm")+xlab("Average # of Seed pods per Plant")+ylab("Total Order Diversity")+theme(panel.border=element_rect(color="black",size=1,fill=NA))+geom_text(aes(x=4.25, y=9.25, label =lm_orderpod(LUNIpollen)), size=4, parse = TRUE)


lm_hemipod <- function(LUNIpollen){
    m <- lm(avgpod ~ hemipteraabundance, LUNIpollen);
    eq <- substitute(italic(y) == a + b%.%italic(x)*","~~italic(R)^2~"="~r2, 
         list(a = format(coef(m)[1], digits = 3), 
              b = format(coef(m)[2], digits = 2), 
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq));
    }
hemi_pod <- ggplot(aes(x=avgpod,y=hemipteraabundance),data=LUNIpollen)+geom_point()+geom_smooth(method = "lm")+xlab("Average # of Seed pods per Plant")+ylab("Total Diversity of Hemipterans")+theme(panel.border=element_rect(color="black",size=1,fill=NA))+geom_text(aes(x=4.25, y=9.25, label =lm_hemipod(LUNIpollen)), size=4, parse = TRUE)


grid.arrange(order_pod,hemi_pod)
```

```{r}
summary(lm(predatorabudance~herbivory, data=LUNIpollen))
plot(predatorabudance~herbivory, data=LUNIpollen)

summary(lm(predperplant~herbivory, data=LUNIpollen))
plot(predperplant~herbivory, data=LUNIpollen)

summary(lm(predatordiversity~herbivory, data=LUNIpollen))
plot(predatordiversity~herbivory, data=LUNIpollen)

summary(lm(herbivorediversity~herbivory, data=LUNIpollen)) #sig 
plot(herbivorediversity~herbivory, data=LUNIpollen)

lm_diverseherb <- function(LUNIpollen){
    m <- lm(herbivorediversity~herbivory, LUNIpollen);
    eq <- substitute(italic(y) == a + b%.%italic(x)*","~~italic(R)^2~"="~r2, 
         list(a = format(coef(m)[1], digits = 3), 
              b = format(coef(m)[2], digits = 2), 
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq));
    }
diverse_herb <- ggplot(aes(x=herbivorediversity,y=herbivory),data=LUNIpollen)+geom_point()+geom_smooth(method = "lm")+xlab("Herbivore Diversity")+ylab("Proportion of L. nipomensis experiencing Herbivory")+theme(panel.border=element_rect(color="black",size=1,fill=NA))+geom_text(aes(x=6.5, y=1, label =lm_hemiherb(LUNIpollen)), size=4, parse = TRUE)

summary(lm(herbivoreperplant~herbivory, data=LUNIpollen))
plot(herbivoreperplant~herbivory, data=LUNIpollen)

summary(lm(herbivoreabundance~herbivory, data=LUNIpollen))
plot(herbivorepeabundance~herbivory, data=LUNIpollen)

summary(lm(hemipteraperplant~herbivory, data=LUNIpollen))
plot(hemipteraperplant~herbivory, data=LUNIpollen)

summary(lm(coleopteraperplant~herbivory, data=LUNIpollen))
plot(coleopteraperplant~herbivory, data=LUNIpollen)

summary(lm(thripsperplant~herbivory, data=LUNIpollen))
plot(thripsperplant~herbivory, data=LUNIpollen)

summary(lm(orderdiversity~herbivory, data=LUNIpollen)) #
plot(orderdiversity~herbivory, data=LUNIpollen)

summary(lm(hemipteradiversity~herbivory, data=LUNIpollen)) #sig
plot(hemipteradiversity~herbivory, data=LUNIpollen)

summary(lm(hemipteraabundance~herbivory, data=LUNIpollen)) #
plot(hemipteraabundance~herbivory, data=LUNIpollen)

summary(lm(dipteradiversity~herbivory, data=LUNIpollen)) #
plot(dipteradiversity~herbivory, data=LUNIpollen)

summary(lm(dipteraabundance~herbivory, data=LUNIpollen))
plot(dipteraabundance~herbivory, data=LUNIpollen)

summary(lm(hymenopteradiversity~herbivory, data=LUNIpollen))
plot(hymenopteradiversity~herbivory, data=LUNIpollen)

summary(lm(hymenopteraabudnance~herbivory, data=LUNIpollen))
plot(hymenopteraabudnance~herbivory, data=LUNIpollen)

summary(lm(CLAMnum~herbivory, data=LUNIpollen))
plot(CLAMnum~herbivory, data=LUNIpollen)

summary(lm(thrips~herbivory, data=LUNIpollen))
plot(thrips~herbivory, data=LUNIpollen)

lm_hemiherb <- function(LUNIpollen){
    m <- lm(herbivory ~ hemipteradiversity, LUNIpollen);
    eq <- substitute(italic(y) == a + b%.%italic(x)*","~~italic(R)^2~"="~r2, 
         list(a = format(coef(m)[1], digits = 3), 
              b = format(coef(m)[2], digits = 2), 
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq));
    }
hemi_herb <- ggplot(aes(x=herbivory,y=hemipteradiversity),data=LUNIpollen)+geom_point()+geom_smooth(method = "lm")+xlab("Proportion of L. nipomensis experiencing Herbivory")+ylab("Total Diversity of Hemipterans")+theme(panel.border=element_rect(color="black",size=1,fill=NA))+geom_text(aes(x=.5, y=2.5, label =lm_hemiherb(LUNIpollen)), size=4, parse = TRUE)


grid.arrange(herb_plant,diverse_herb,ncol=2)

```

```{r}
summary(lm(predatorabudance~individuals, data=LUNIpollen))
plot(predatorabudance~individuals, data=LUNIpollen)

summary(lm(predatordiversity~individuals, data=LUNIpollen))
plot(predatordiversity~individuals, data=LUNIpollen)

summary(lm(herbivorediversity~individuals, data=LUNIpollen)) # 
plot(herbivorediversity~individuals, data=LUNIpollen)


summary(lm(herbivoreabundance~individuals, data=LUNIpollen))
plot(herbivorepeabundance~individuals, data=LUNIpollen)


summary(lm(orderdiversity~individuals, data=LUNIpollen)) #suggested
plot(orderdiversity~individuals, data=LUNIpollen)

summary(lm(hemipteradiversity~individuals, data=LUNIpollen)) #
plot(hemipteradiversity~individuals, data=LUNIpollen)

summary(lm(hemipteraabundance~individuals, data=LUNIpollen)) #
plot(hemipteraabundance~individuals, data=LUNIpollen)

summary(lm(dipteradiversity~individuals, data=LUNIpollen)) #
plot(dipteradiversity~individuals, data=LUNIpollen)

summary(lm(dipteraabundance~individuals, data=LUNIpollen))
plot(dipteraabundance~individuals, data=LUNIpollen)

summary(lm(hymenopteradiversity~individuals, data=LUNIpollen)) #sig
plot(hymenopteradiversity~individuals, data=LUNIpollen)

summary(lm(hymenopteraabudnance~individuals, data=LUNIpollen))
plot(hymenopteraabudnance~individuals, data=LUNIpollen)

summary(lm(CLAMnum~individuals, data=LUNIpollen))
plot(CLAMnum~individuals, data=LUNIpollen)

summary(lm(thrips~individuals, data=LUNIpollen))
plot(thrips~individuals, data=LUNIpollen)

lm_orderpop <- function(LUNIpollen){
    m <- lm(orderdiversity ~ individuals, LUNIpollen);
    eq <- substitute(italic(y) == a + b%.%italic(x)*","~~italic(R)^2~"="~r2, 
         list(a = format(coef(m)[1], digits = 3), 
              b = format(coef(m)[2], digits = 2), 
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq));
    }
order_pop <- ggplot(aes(x=individuals,y=orderdiversity),data=LUNIpollen)+geom_point()+geom_smooth(method = "lm")+xlab("L. nipomensis Popultion Size")+ylab("Total Order Diversity")+theme(panel.border=element_rect(color="black",size=1,fill=NA))+geom_text(aes(x=35, y=8, label =lm_orderpop(LUNIpollen)), size=4, parse = TRUE)

lm_hymenpop <- function(LUNIpollen){
    m <- lm(hymenopteradiversity ~ individuals, LUNIpollen);
    eq <- substitute(italic(y) == a + b%.%italic(x)*","~~italic(R)^2~"="~r2, 
         list(a = format(coef(m)[1], digits = 3), 
              b = format(coef(m)[2], digits = 2), 
             r2 = format(summary(m)$r.squared, digits = 3)))
    as.character(as.expression(eq));
    }
hymen_pop <- ggplot(aes(x=individuals,y=hymenopteradiversity),data=LUNIpollen)+geom_point()+geom_smooth(method = "lm")+xlab("L. nipomensis Population Size")+ylab("Hymenoptera Diversity")+theme(panel.border=element_rect(color="black",size=1,fill=NA))+geom_text(aes(x=35, y=2, label =lm_hymenpop(LUNIpollen)), size=4, parse = TRUE)


```


