---
title: "nipomo2019"
author: "Justin Luong"
date: "August 21, 2019"
output: word_document
editor_options: 
  chunk_output_type: console
---

```{r Load data and packages}
nipomo2019 <- read.csv("C:/Users/bacon/Box/CCBER Stuff/Nipomo Lupine/Datasheets/nipomolupine2019.csv")

nipomo2019 <- nipomo2019[!apply(is.na(nipomo2019) | nipomo2019 == "", 1, all),] # remove blank rows

fiveyeardata <-read.csv("C:/Users/bacon/Box/CCBER Stuff/Nipomo Lupine/Datasheets/nipomo5years.csv")

fiveyeardata$current.year <- as.factor(as.character(fiveyeardata$current.year))



require(plyr)
require(ggplot2)
library(grid)
library(gridExtra)
library(ggplot2)
library(nnet)
library(foreign)
library(agricolae)
library(ggsignif)
library(multcomp)
library(car)
library(e1071)

cbbPalette <- c("#56B4E9", "#999999", "#E69F00", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
```

```{r Plot Level - By Year - Overall Germination & Seed Production}
seeded <- subset(fiveyeardata, totalseedpods>0)
germinated <- subset(fiveyeardata, germination>0)


summary(aov(totalseedpods~as.factor(current.year),data=seeded))
TukeyHSD(aov(totalseedpods~as.factor(current.year),data=seeded))

seedingbyyear <- ddply(seeded, c("current.year"), summarise,
                       avgseeds = mean(totalseedpods),
                       totalseeds = sum(totalseedpods),
                       SEseeds = sd(totalseedpods)/(sqrt(length(totalseedpods))))

seedingbyyear$current.year <- as.factor(seedingbyyear$current.year)

seedyeargraph <- ggplot(aes(x=current.year, y=avgseeds, ymax=avgseeds+SEseeds, ymin=avgseeds-SEseeds, color=current.year, fill=current.year),data=seedingbyyear)+geom_bar(stat="identity", position="dodge", color="black", show.legend = F)+ylab("Average Seedpod Production")+xlab("Year Monitored")+theme(panel.border=element_rect(color="black", size=1, fill=NA))+geom_errorbar(position=position_dodge(), color="black",width = 0.9)+scale_fill_manual(values=cbbPalette)

summary(aov(as.numeric(percent)~as.factor(current.year),data=fiveyeardata))
TukeyHSD(aov(as.numeric(percent)~as.factor(current.year),data=fiveyeardata))

germbyyear <- ddply(fiveyeardata, c("current.year"), summarise,
                       avgpercentgerm = mean(as.numeric(percent)),
                    totalgerm = sum(germination),
                       SEpercentgerm = sd(as.numeric(percent))/(sqrt(length(as.numeric(percent)))))

germbyyear$current.year<-as.factor(germbyyear$current.year)

germyeargraph <- ggplot(aes(x=current.year, y=avgpercentgerm, ymax=avgpercentgerm+SEpercentgerm, ymin=avgpercentgerm-SEpercentgerm, color=current.year, fill=current.year),data=germbyyear)+geom_bar(stat="identity", position="dodge", color="black", show.legend = F)+ylab("Average Percent Germination")+xlab("Year Monitored")+theme(panel.border=element_rect(color="black", size=1, fill=NA))+geom_errorbar(position=position_dodge(), color="black",width = 0.9)+scale_fill_manual(values=cbbPalette)


skewness(sqrt(germinated$proportionseeded))

summary(aov(proportionseeded~as.factor(current.year),data=germinated))
TukeyHSD(aov(proportionseeded~as.factor(current.year),data=germinated))


proportionbyyear <- ddply(germinated, c("current.year"), summarise,
                       avgproportion = mean(proportionseeded),
                       SEproportion = sd(proportionseeded)/(sqrt(length(proportionseeded))))

proportionbyyear$current.year<-as.factor(proportionbyyear$current.year)

proportionyeargraph <- ggplot(aes(x=current.year, y=avgproportion, ymax=avgproportion+SEproportion, ymin=avgproportion-SEproportion, color=current.year, fill=current.year),data=proportionbyyear)+geom_bar(stat="identity", position="dodge", color="black", show.legend = F)+ylab("Avg Proportion of Germinants that Reached Reproduction")+xlab("Year Monitored")+theme(panel.border=element_rect(color="black", size=1, fill=NA))+geom_errorbar(position=position_dodge(), color="black",width = 0.9)+scale_fill_manual(values=cbbPalette)

grid.arrange(germyeargraph, seedyeargraph,proportionyeargraph,ncol=2)

skewness(sqrt(as.numeric(fiveyeardata$percent)))
t.test(as.numeric(percent)~previous, data=fiveyeardata) # previous seeding had no effect on percent germination

t.test(germination~previous, data=fiveyeardata)  #Plots that previously had 
t.test(reproductive~previous, data=fiveyeardata)

```


```{r - Percent Germination vs Topography, Aspect, Slope, Caging at Plot Level}
summary(aov(as.numeric(percent)~Topo*cage,data=fiveyeardata))  #sig*
summary(aov(as.numeric(percent)~Topo*caged,data=fiveyeardata)) 
TukeyHSD(aov(as.numeric(percent)~Topo*cage, data=fiveyeardata)) # no differences between caging treatments, just caging - so just use caged
TukeyHSD(aov(as.numeric(percent)~Topo*caged, data=fiveyeardata))

#Topography
Germ_Topo <- ddply(fiveyeardata, c("Topo"),summarise,
                   avgpercentgerm = mean(as.numeric(percent)),
                   totalgerm = sum(germination),
                   error = sd(as.numeric(percent))/(sqrt(length(as.numeric(percent)))))



GermGraph_Topo <- ggplot(aes(x=Topo,y=avgpercentgerm,fill=Topo,color=Topo),data=Germ_Topo)+geom_bar(stat="identity",position="dodge",color="black",show.legend=FALSE)+scale_fill_manual(values=cbbPalette)  + geom_errorbar(aes(ymax=avgpercentgerm+error, ymin=avgpercentgerm-error),position="dodge",color="black",width=0.9) + ylab("Avg % Germination")+xlab("Topography")+theme(panel.border=element_rect(color="black",size=1,fill=NA))

#Slope and Aspect Separate
summary(aov(as.numeric(percent)~Aspect*caged,data=fiveyeardata))  #Sig**
TukeyHSD(aov(as.numeric(percent)~Aspect*caged, data=fiveyeardata))

Germ_Aspect <-ddply(fiveyeardata, c("Aspect"),summarise,
                   avgpercentgerm = mean(as.numeric(percent)),
                   error = sd(as.numeric(percent))/(sqrt(length(as.numeric(percent)))))

Germ_Slope <-ddply(fiveyeardata, c("Slope"),summarise,
                   avgpercentgerm = mean(as.numeric(percent)),
                   error = sd(as.numeric(percent))/(sqrt(length(as.numeric(percent)))))

GermGraph_Aspect <- ggplot(aes(x=Aspect,y=avgpercentgerm,fill=Aspect,color=Aspect),data=Germ_Aspect)+geom_bar(stat="identity",position="dodge",color="black",show.legend=FALSE)+scale_fill_manual(values=cbbPalette)  + geom_errorbar(aes(ymax=avgpercentgerm+error, ymin=avgpercentgerm-error),position="dodge",color="black",width=0.9) + ylab("Avg % Germination")+xlab("Aspect")+theme(panel.border=element_rect(color="black",size=1,fill=NA))

GermGraph_Slope <- ggplot(aes(x=Slope,y=avgpercentgerm,fill=Slope,color=Slope),data=Germ_Slope)+geom_bar(stat="identity",position="dodge",color="black",show.legend=FALSE)+scale_fill_manual(values=cbbPalette)  + geom_errorbar(aes(ymax=avgpercentgerm+error, ymin=avgpercentgerm-error),position="dodge",color="black",width=0.9) + ylab("Avg % Germination")+xlab("Slope")+theme(panel.border=element_rect(color="black",size=1,fill=NA))

GerminationPercentage <-grid.arrange(GermGraph_Topo, arrangeGrob(GermGraph_Aspect,GermGraph_Slope, ncol=2), ncol=1, heights=c(1,1))

```

```{r Plot Level - Seed Pod Production by Topography}

summary(aov(totalseedpods~Topo*cage,data=seeded))  #significant
summary(aov(totalseedpods~Slope*cage,data=seeded))   #nonsignifi
summary(aov(totalseedpods~Aspect*cage,data=seeded))  #significant - aspect more important

Seedpod_Topo <- ddply(seeded, c("Topo"),summarise,
                   avgseedpods = mean(totalseedpods),
                   error = sd(totalseedpods)/(sqrt(length(totalseedpods))))



Seedpod_TopoGraph_Topo <- ggplot(aes(x=Topo,y=avgseedpods,fill=Topo,color=Topo),data=Seedpod_Topo)+geom_bar(stat="identity",position="dodge",color="black",show.legend=FALSE)+scale_fill_manual(values=cbbPalette)  + geom_errorbar(aes(ymax=avgseedpods+error, ymin=avgseedpods-error),position="dodge",color="black",width=0.9) + ylab("Avg Seedpod Production")+xlab("Topography")+theme(panel.border=element_rect(color="black",size=1,fill=NA))

```


```{r caging and herbivory by Plot}
summary(aov(as.numeric(percent)~Topo*caged, data=fiveyeardata))   #sig**
TukeyHSD(aov(as.numeric(percent)~Topo*caged, data=fiveyeardata))

t.test(as.numeric(percent)~caged, data=fiveyeardata)

Germ_Cage <- ddply(fiveyeardata, c("caged"),summarise,
                   avgpercentgerm = mean(as.numeric(percent)),
                   error = sd(as.numeric(percent))/(sqrt(length(as.numeric(percent)))))

GermGraph_Cage <- ggplot(aes(x=caged,y=avgpercentgerm,fill=caged,color=caged),data=Germ_Cage)+geom_bar(stat="identity",position="dodge",color="black",show.legend=FALSE)+scale_fill_manual(values=cbbPalette)  + geom_errorbar(aes(ymax=avgpercentgerm+error, ymin=avgpercentgerm-error),position="dodge",color="black",width=0.9) + ylab("Avg % Germination")+xlab("Presence of Caging")+theme(panel.border=element_rect(color="black",size=1,fill=NA))

summary(aov(totalseedpods~Topo*caged, data=seeded))
TukeyHSD(aov(totalseedpods~Topo+caged, data=seeded))

t.test(totalseedpods~caged, data=seeded)

Seeds_cage <- ddply(seeded, c("caged"),summarise,
                   avgseeds = mean(totalseedpods),
                   error = sd(totalseedpods)/(sqrt(length(totalseedpods))))

SeedsGraph_Cage <- ggplot(aes(x=caged,y=avgseeds,fill=caged,color=caged),data=Seeds_cage)+geom_bar(stat="identity",position="dodge",color="black",show.legend=FALSE)+scale_fill_manual(values=cbbPalette)  + geom_errorbar(aes(ymax=avgseeds+error, ymin=avgseeds-error),position="dodge",color="black",width=0.9) + ylab("Avg Seed Pod Production")+xlab("Presence of Caging")+theme(panel.border=element_rect(color="black",size=1,fill=NA))

EffectofCaging <- grid.arrange(GermGraph_Cage,SeedsGraph_Cage,ncol=2)



percentcage <- ddply(germinated, c("caged","rep"), summarise,
                     avgseeds = mean(totalseedpods, na.rm = TRUE),
                     percentsevere = sum(severity=="Severe")/length(severity),
                     percentmoderate = sum(severity=="Moderate")/length(severity),
                     percentmild = sum(severity=="Mild")/length(severity),
                     percentnone = sum(severity=="No Herbivory")/length(severity))

severepercent <- ddply(percentcage, "caged", summarise,
                      avg = mean(percentsevere)*100,
                      SE = (sd(percentsevere)/sqrt(length(percentsevere))*100))

mildpercent <- ddply(percentcage, "caged", summarise,
                      avg = mean(percentmild)*100,
                      SE = (sd(percentmild)/sqrt(length(percentmild))*100))

noherbivorypercent <- ddply(percentcage, "caged", summarise,
                      avg = mean(percentnone)*100,
                      SE = (sd(percentnone)/sqrt(length(percentnone))*100))



t.test(percentmild~caged, data=percentcage)
t.test(percentnone~caged, data=percentcage)

t.test(percentsevere~caged, data=percentcage)
TukeyHSD(aov(percentsevere~caged,data=percentcage))

cage_v_severe <- ggplot(aes(x=caged,y=avg, fill = caged),data=severepercent)+scale_fill_manual(values=cbbPalette)+geom_bar(stat="identity",position="dodge",color="black", show.legend = FALSE)+geom_errorbar(aes(ymax=avg+SE,ymin=avg-SE,position="dodge"),color="black",width=0.9)+xlab("Presence of Caging")+ylab("Average Proportion of Herbivory being Severe ")+theme(panel.border=element_rect(color="black",size=1,fill=NA))

cage_v_mild <- ggplot(aes(x=caged,y=avg, fill = caged),data=mildpercent)+scale_fill_manual(values=cbbPalette)+geom_bar(stat="identity",position="dodge",color="black", show.legend = FALSE)+geom_errorbar(aes(ymax=avg+SE,ymin=avg-SE,position="dodge"),color="black",width=0.9)+xlab("Presence of Caging")+ylab("Average Proportion of Herbivory being Mild ")+theme(panel.border=element_rect(color="black",size=1,fill=NA))

cage_v_noherbivory <- ggplot(aes(x=caged,y=avg, fill = caged),data=noherbivorypercent)+scale_fill_manual(values=cbbPalette)+geom_bar(stat="identity",position="dodge",color="black", show.legend = FALSE)+geom_errorbar(aes(ymax=avg+SE,ymin=avg-SE,position="dodge"),color="black",width=0.9)+xlab("Presence of Caging")+ylab("Average Proportion of Herbivory being Absent (0-100%)")+theme(panel.border=element_rect(color="black",size=1,fill=NA))


HerbivorySeverityPercentage <-grid.arrange(cage_v_noherbivory, arrangeGrob(cage_v_mild,cage_v_severe, ncol=2), ncol=1, heights=c(1,1))

severeseeds <- ddply(seeded, "severity", summarise,
                     total = sum(totalseedpods),
                     averageseeds = mean(totalseedpods),
                     SE = sd(totalseedpods)/sqrt(length(totalseedpods)),
                     order = 0)

summary(aov(earlydeath~severity,data=germinated))
TukeyHSD(aov(earlydeath~severity,data=germinated))


summary(aov(totalseedpods~severity,data=seeded))
TukeyHSD(aov(totalseedpods~severity,data=seeded))

####GENERAL CONTRASTS#######

levels(seeded$severity) # look at order of Treatment groups (# Hypothesis = 1-# of factors )
# setting up contrasts for each hypothesis

seedproductionvseverityh2 <- c(-0.5,1,-0.5) #hypothese = herbivory decreases seed production

seedproductionvseverityh4 <- c(1,-.25,-0.75) #hypothesis = mild herbivory increases seed production, severe herbivory decreases seed production

seedproductionvseveritymat.temp <- rbind(constant=1/3, seedproductionvseverityh2, seedproductionvseverityh4) #create matrix of contrasts
seedproductionvseveritymat <- solve(seedproductionvseveritymat.temp) # get inverse of matrix - must do this if contrasts are nonorthogonal
seedproductionvseveritymat <- seedproductionvseveritymat[,-1] # drop first column

seedproductionvseveritylmout2 <- lm(totalseedpods~severity, data = seeded, contrasts=list(severity = seedproductionvseveritymat)); summary(seedproductionvseveritylmout2) # look at p-values to accept/reject hypotheses
# based on p-values...
# accept H1 - no cage artifacts
# reject H2 - total exclusion is diff from no exclusion => grazers affect seedling establishment
# reject H3 - total exclusion is diff from partial exclusion 
# reject H4 - rabbit diff from deer (look at graph to determine if they inhibit seedling establishment more or less than deer)

####END GENERAL CONTRASTS#######



Severeseedsgraph <- ggplot(aes(x=severity,y=averageseeds, fill = severity),data=severeseeds)+geom_bar(stat="identity",position="dodge",color="black", show.legend = FALSE)+geom_errorbar(aes(ymax=averageseeds+SE,ymin=averageseeds-SE,position="dodge"),color="black",width=0.9)+xlab("Degree of Herbivory")+ylab("Average Seed Pod Production")+theme(panel.border=element_rect(color="black",size=1,fill=NA))+scale_fill_manual(values=cbbPalette)



summary(aov(earlydeath~severity,data=germinated))
TukeyHSD(aov(earlydeath~severity,data=germinated)) # no effect of herbivory severity on early death
t.test(earlydeath~eaten, data=germinated)


severityearlydeath <- ddply(germinated, "severity", summarise,
                     avgearlydeath = mean(earlydeath),
                     SE = sd(earlydeath)/sqrt(length(earlydeath)),
                     order = 0)

severedeathgraph <- ggplot(aes(x=severity,y=avgearlydeath, fill = severity),data=severityearlydeath)+geom_bar(stat="identity",position="dodge",color="black", show.legend = FALSE)+geom_errorbar(aes(ymax=avgearlydeath+SE,ymin=avgearlydeath-SE,position="dodge"),color="black",width=0.9)+xlab("Degree of Herbivory")+ylab("Average Number of Early Deaths")+theme(panel.border=element_rect(color="black",size=1,fill=NA))+scale_fill_manual(values=cbbPalette)

summary(aov(reproductive~severity,data=germinated))
TukeyHSD(aov(reproductive~severity,data=germinated))

severityreproductive <- ddply(germinated, "severity", summarise,
                     avgreproductive = mean(reproductive),
                     SE = sd(reproductive)/sqrt(length(reproductive)),
                     order = 0)

severereproductivegraph <- ggplot(aes(x=severity,y=avgreproductive, fill = severity),data=severityreproductive)+geom_bar(stat="identity",position="dodge",color="black", show.legend = FALSE)+geom_errorbar(aes(ymax=avgreproductive+SE,ymin=avgreproductive-SE,position="dodge"),color="black",width=0.9)+xlab("Degree of Herbivory")+ylab("Average Number of Early Deaths")+theme(panel.border=element_rect(color="black",size=1,fill=NA))+scale_fill_manual(values=cbbPalette)

grid.arrange(cage_v_severe, severereproductivegraph, ncol=2)

```

```{r Plot Level Seed Bank Analysis}

summary(aov(bank~Topo, data=fiveyeardata)) #topography signficant on seed bank
TukeyHSD(aov(bank~Topo, data=fiveyeardata))

summary(aov(bank~Slope, data=fiveyeardata))  # no effect of slope on its own

summary(aov(bank~Aspect, data=fiveyeardata)) # effect of aspect sig of seedbank
TukeyHSD(aov(bank~Aspect, data=fiveyeardata))


#Topography
Bank_Topo <- ddply(fiveyeardata, c("Topo"),summarise,
                   avgbank = mean(bank),
                   totalbank = sum(bank),
                   error = sd(bank)/(sqrt(length(bank))))



BankGraph_Topo <- ggplot(aes(x=Topo,y=avgbank,fill=Topo,color=Topo),data=Bank_Topo)+geom_bar(stat="identity",position="dodge",color="black",show.legend=FALSE)+scale_fill_manual(values=cbbPalette)  + geom_errorbar(aes(ymax=avgbank+error, ymin=avgbank-error),position="dodge",color="black",width=0.9) + ylab("Average Seedbank Accumulated per Plot")+xlab("Topography")+theme(panel.border=element_rect(color="black",size=1,fill=NA))

#Slope and Aspect Separate
summary(aov(bank~Aspect*caged,data=fiveyeardata))  #Sig**
TukeyHSD(aov(bank~Aspect*caged, data=fiveyeardata))

bank_Aspect <-ddply(fiveyeardata, c("Aspect"), summarise,
                   avgbank = mean(bank),
                   error = sd(bank)/(sqrt(length(bank))))

bank_Slope <-ddply(fiveyeardata, c("Slope"),summarise,
                   avgbank = mean(bank),
                   error = sd(bank)/(sqrt(length(bank))))

BankGraph_Aspect <- ggplot(aes(x=Aspect,y=avgbank,fill=Aspect,color=Aspect),data=bank_Aspect)+geom_bar(stat="identity",position="dodge",color="black",show.legend=FALSE)+scale_fill_manual(values=cbbPalette)  + geom_errorbar(aes(ymax=avgbank+error, ymin=avgbank-error),position="dodge",color="black",width=0.9) + ylab("Average Seedbank Accumulated per Plot")+xlab("Aspect")+theme(panel.border=element_rect(color="black",size=1,fill=NA))

BankGraph_Slope <- ggplot(aes(x=Slope,y=avgbank,fill=Slope,color=Slope),data=bank_Slope)+geom_bar(stat="identity",position="dodge",color="black",show.legend=FALSE)+scale_fill_manual(values=cbbPalette)  + geom_errorbar(aes(ymax=avgbank+error, ymin=avgbank-error),position="dodge",color="black",width=0.9) + ylab("Average Seedbank Accumulated per Plot")+xlab("Slope")+theme(panel.border=element_rect(color="black",size=1,fill=NA))

BankbyTopography <-grid.arrange(BankGraph_Topo, arrangeGrob(BankGraph_Aspect,BankGraph_Slope, ncol=2), ncol=1, heights=c(1,1))


summary(lm(bank~germination, data = fiveyeardata))
attach(fiveyeardata)
plot(bank~germination)
abline(lm(bank~germination))
detach(fiveyeardata)

summary(lm(bank~proportionseeded, data = fiveyeardata))
attach(fiveyeardata)
plot(bank~proportionseeded)
abline(lm(bank~proportionseeded))
detach(fiveyeardata)

multi_lm <- lm(formula = bank ~ janrain + aprilrain + mayrain  + totalrain, data = fiveyeardata) #run multiple regression
summary(multi_lm)      # view results                         #k = number of parameters (y + all x + 1 (for the residuals))
multi_AICc <- AIC(multi_lm) + 2 * 6 * (6 + 1) / (324 - 6 -1)     #subset AIC scores AIC correction factor = [2*k(k+1)/(N-k-1)]
multi_AICc                                        
vif(multi_lm)
```



```{r Individual Level - 2019 Only - Overall Germination & Seed Production}
nipomo2019

summary(aov(totalherb~cage,data=nipomo2019)) # no effect of cage type on total herb
summary(aov(totalleafherb~cage,data=nipomo2019))  #no effect of cage type on veg herb
summary(aov(totalseedherb~cage, data=seededin2019)) #no effect of reproductive type on veg herb

seededin2019 <- subset(nipomo2019, seedpods > 0)

t.test(seedpods~Eaten,data=seededin2019) # no significant effect on being "eaten"
t.test(totalleafherb~Caged,data=nipomo2019) # sig effect of cage presence on vegetative herb
t.test(totalseedherb~Caged, data=seededin2019) #no sig of cage presence on reproductive herb

attach(seededin2019)
summary(lm(log(seedpods)~seedherb, data = seededin2019))
plot(log(seedpods)~seedherb)
detach(seededin2019)

skewness(log(seededin2019$seedpods))
skewness(seeded$totalseedpods)

t.test(totalherb~as.factor(previous),data=nipomo2019)

summary(aov(bank~Topo, data=fiveyeardata)) #topography signficant on seed bank
TukeyHSD(aov(bank~Topo, data=fiveyeardata))

summary(aov(bank~Slope, data=fiveyeardata))  # no effect of slope on its own

summary(aov(bank~Aspect, data=fiveyeardata)) # effect of aspect sig of seedbank
TukeyHSD(aov(bank~Aspect, data=fiveyeardata))



```

